import React from 'react'
import styles from "./PlotSection.module.css";

const PlotSection = () => {

  const plots = [
    { src: "/download1.png", alt: "Plot1" },
    { src: "/download2.png", alt: "Plot2" },
    { src: "/download3.png", alt: "Plot3" },
    { src: "/download4.jpeg", alt: "Plot4" },
  ];

  return (
    <div className={styles.grid}>
      {
        plots.length > 0 ? plots.map((plot, index)=>{
          return(
            <div key={index} className={styles.card}>
              <img src={plot['src']} alt={plot['alt']} />
              <div className={styles.plotTitle}>{plot['alt']}</div>
              <div className={styles.plotActions}>
                <button className={styles.plotAction} title="Download">📥</button>
                <button className={styles.plotAction} title="Fullscreen">🔍</button>
              </div>
            </div>
          );
        }) : (
          <div className={styles.emptyState}>
            <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
            <h3>No visualizations yet</h3>
            <p>Your data visualizations and plots will appear here once generated by the analysis agent.</p>
          </div>
        )
      }
    </div>
  )
}

export default PlotSection
